version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/donuts
permissions:
  - object: /var/www/donuts
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dotnet.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/restore_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ec2-user
