version: 0.0
os: linux
files:
  - source: donuts
    destination: /var/www
  - source: scripts/website.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 10
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 10
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 10
